### ISSUE TITLE
Accept `suggestions` in `fromFixture`

### ISSUE THREAD

**Issue by rafaelss95** [cartant/eslint-etc#3]
Currently with `fromFixture` we can test **fixable** rules really well, without all the verbosity of `errors: [...]`, however the same isn't possible with **suggestions**. Not sure if it's something you'd consider, but I'd like to write something like:

```ts
fromFixture(
  stripIndent`
  export const getCount: MemoizedSelector<any, any> = (state: AppState) => state.feature,
               ~~~~~~~~ [${messageId} { "name": "selectCount" }]`,
  {
    suggestions: [
      {
        messageId: prefixSelectorsWithSelectSuggest as MessageIds,
        output: stripIndent`
          export const selectCount: MemoizedSelector<any, any> = (state: AppState) => state.feature`,
      },
    ],
  },
),
```

(Note that this can be even worse when a snippet has multiple reports 😞).

... instead of:

```ts
{
  code: stripIndent`
  export const getCount: MemoizedSelector<any, any> = (state: AppState) => state.feature`,
  errors: [
    {
      column: 14,
      endColumn: 22,
      line: 1,
      messageId: prefixSelectorsWithSelect,
      data: {
        name: 'selectCount',
      },
      suggestions: [
        {
          messageId: prefixSelectorsWithSelectSuggest as MessageIds,
          output: stripIndent`
          export const selectCount: MemoizedSelector<any, any> = (state: AppState) => state.feature`,
        },
      ],
    },
  ],
},
```

This might be also great in cases where we have both suggestion and fix together.

cc/ @timdeschryver

**Comment by cartant** [comment]
It should be possible to do something along those lines for simple, single-error fixtures. And it should be possible to extend the DSL so that we can get it to work with multi-error fixtures, too. I'll have a think about it. I have some ideas.

**Comment by cartant** [comment]
Added support for `suggestions`. See the tests for usage.

By default, fixtures will assign any specified `suggestions` to all errors in a fixture:

https://github.com/cartant/eslint-etc/blob/14c31df4a5124b928c53d82529063c6f5f888add/source/from-fixture-spec.ts#L155-L170

If there are multiple errors, you can specify the suggestions associated with each error by index:

https://github.com/cartant/eslint-etc/blob/14c31df4a5124b928c53d82529063c6f5f888add/source/from-fixture-spec.ts#L245-L274

**Comment by rafaelss95** [comment]
Thanks for that @cartant. It was really fast and I was impressed how you managed to make it so flexible (especially for the `suggest [index here]`, I really ❤️ this)! 🚀 

---

One thing I noticed that maybe (most likely) doesn't have much to do with this new implementation is that `fromFixture` doesn't seem to be able to get the type inference correctly. I'm always getting an `eslint.InvalidTestCase<never, never>` and this is perhaps the reason why I believe we're having to cast manually the `MessageIds` when mixing the approaches (`fromFixture` + "native") as you can see in this example [here](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/c089ac5b9875377b490681992ab3d3d15607a4b7/tests/rules/prefer-one-generic-in-create-for-feature-selector.test.ts#L32)... or maybe I'm missing something else.

**Comment by cartant** [comment]
`TMessageIds` should be threaded through the option-less signature in `4.2.5`, so the type assertion on the suggestion `messageId` shouldn't be required when mixing approaches.
