### ISSUE TITLE
Accept immutable arrays within `fromFixture`

### ISSUE THREAD

**Issue by rafaelss95** [cartant/eslint-etc#4]
Consider this scenario:

```ts
type MessageIds = ESLintUtils.InferMessageIdsTypeFromRule<typeof rule> // 'preferConcatLatestFrom'
type Options = ESLintUtils.InferOptionsTypeFromRule<typeof rule> // [{ readonly strict: boolean; }]

const valid: TSESLint.RunTests<MessageIds, Options>['valid'] = []
const invalid: TSESLint.RunTests<MessageIds, Options>['invalid'] = [
  fromFixture(``, {
    options: [{ strict: true }], // here I get the error described below
    output: ``,
  }),
]
```

> Type 'InvalidTestCase<"preferConcatLatestFrom", { strict: boolean; }[]>' is not assignable to type 'InvalidTestCase<"preferConcatLatestFrom", Options>'.
  Types of property 'options' are incompatible.
    Type 'readonly { strict: boolean; }[]' is not assignable to type 'readonly [{ strict: boolean; }]'.
      Target requires 1 element(s) but source may have fewer.ts(2322)

So, to fix this, I can either do `options: [{ strict: true }] as const` or `{ output: ..., options: ... } as const` and so the TS is happy, however `fromFixture` doesn't accept readonly arrays...

I believe that it's a simple change:

```diff
- export declare function fromFixture<TMessageIds extends string, TOptions extends unknown[]>
+ export declare function fromFixture<TMessageIds extends string, TOptions extends readonly unknown[]>
```

and

```diff
- suggestions?: eslint.SuggestionOutput<string>[] | null | undefined;
+ suggestions?: readonly eslint.SuggestionOutput<string>[] | null | undefined;
- suggestions?: eslint.SuggestionOutput<TMessageIds>[] | null | undefined;
+ suggestions?: readonly eslint.SuggestionOutput<TMessageIds>[] | null | undefined;
```

Let me know if this case was clear enough to describe the issue (and I'm able to help submitting a PR if that's the case).

**Comment by cartant** [comment]
Closed by #6 and published as 4.2.6.
